---
title: StinaHuglenArt
author: Stina Huglen
email: stina.huglen@outlook.com
description: My portfolio, store and contact information
baseurl: "/stinaart_forestry"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
